#!/usr/bin/env python3


import RPi.GPIO as GPIO
import time



GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
pins = [22,6,13,26]

GPIO.setup(pins, GPIO.OUT, initial=GPIO.HIGH)


while True:
	GPIO.output(pins,1)
	time.sleep(0.10)
	GPIO.output(pins,0)
	time.sleep(0.10)
	
