#!/usr/bin/env python3
import random
import blinky

list = [
	blinky.drag,
	blinky.blink,
	blinky.three,
	blinky.out,
	blinky.jump,
	blinky.spike,
	blinky.space,
	blinky.swipe,
    blinky.base
]


while True:
	random.choice(list)()

