#!/usr/bin/env python2
import subprocess as sp
import time



def  question():
    sp.call("espeak 'Welcome to the question maker, do you want to play? '", shell=True)
    time.sleep(1.5)
    sp.call("espeak ' All questions will be fifty points'",shell=True) 
    time.sleep(1.5)
    sp.call("espeak 'if you got them right '",shell=True)
    time.sleep(1.5)
    sp.call("espeak 'you will have five seconds to answer the questions'",shell=True)
    time.sleep(1.5)
    sp.call("espeak 'First question, name one MLG item '",shell=True)
    time.sleep(3)
    sp.call("espeak 'Question one done, the answers could  be three sixty no scope'",shell=True)
    time.sleep(1.5)
    sp.call("espeak 'Or illuminati, or oooh baby a triple and airhorns and baby lumi'",shell=True)
    time.sleep(1.5)
    sp.call("espeak 'If you got this right, good job, thheeeeeeeee end'",shell=True)
    time.sleep(1.5)

def name():
    sp.call("espeak 'Hello, my name is espeak'",shell=True)
    time.sleep(1.5)
    sp.call("espeak 'What is your name?'",shell=True)
    time.sleep(0.5)
    name = input("espeak 'What is your name? '")
    time.sleep(0.5)
    sp.call("espeak 'Hello, '",shell=True)
    time.sleep(0.25)
    sp.call("espeak" + " '" + name + "'",shell=True)
    time.sleep(1.5)

def story():
    sp.call("espeak 'Ok, before we start, whats your name ' ",shell=True)
    time.sleep(1.5)
    name = input("espeak 'What is this name?'")
    time.sleep(0.5)
    sp.call("espeak" + " '" + name + "'", shell=True)
    time.sleep(1.5)
    sp.call("espeak 'Ok before we start'", shell=True)
    time.sleep(1.0)
    sp.call("espeak 'What is a noun'",shell=True)
    noun1 = input("espeak 'What is your noun?'")
    time.sleep(.5)
    sp.call("espeak 'Ok, what is a verb of your choice'",shell=True)
    time.sleep(.5)
    verb1 = input("espeak 'What is your verb of your choice?'")
    sp.call("espeak 'Ok, what is another noun of your choice'",shell=True)
    time.sleep(.5)
    noun2 = input("espeak 'What is your other noun?'")
    time.sleep(.5)
    sp.call("espeak 'Ok, now we will create a story'",shell=True)
    time.sleep(.5)
    sp.call("espeak 'using your words'",shell=True)
    time.sleep(.5)
    ############Story
    sp.call("espeak 'Once upon a time'",shell=True)
    time.sleep(.5)
    sp.call("espeak 'There was a'",shell=True)
    time.sleep(.5)
    sp.call("espeak" + " '" + noun1 + "'", shell=True)
    time.sleep(.5)
    sp.call("espeak 'Who liked to'",shell=True)
    time.sleep(.5)
    sp.call("espeak" + " '" + verb1 + "'",shell=True)
    time.sleep(.5)
    sp.call("espeak 'On'",shell=True)
    time.sleep(0.5)
    sp.call("espeak" + " '" + noun2 + "'",shell=True)
    time.sleep(0.5)
    sp.call("espeak 'The end'",shell=True)
    time.sleep(1.5)

