#!/usr/bin/env python3

import espeak_mine
import random


 
list = [
        #espeak_mine.name(),
        #espeak_mine.question(),
        espeak_mine.story()
]
     
         
while True:
    random.choice(list)
