#!/usr/bin/env python2
from espeak import espeak
import time
espeak.synth("Welcome to the question maker, do you want to play? ")
time.sleep(1)
espeak.synth("All questions will be fifty points") 
time.sleep(1)
espeak.synth("if you got them right ")
time.sleep(1)
esiipeak.synth("You will have") 
time.sleep(1)
espeak.synth("five seconds to answer the questions ")
time.sleep(1)
espeak.synth("First question, name one MLG item ")
time.sleep(5)
espeak.synth("Question one done, the answers could  be three sixty no scope")
time.sleep(0.25)
espeak.synth("Or illuminati,      or oooh baby a triple and     airhorns")
time.sleep(1)
